image: python:3.6-alpine

services:
  - postgres:alpine

before_script:
  - apk add --no-cache postgresql-dev musl-dev gcc
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test